export const LEGAL={
privacy:{kicker:"Privacy",title:"Privacy Policy",summary:"A clear explanation of how LifeOS handles information. Replace implementation placeholders with verified production data before publication.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>1. Scope</h2><p>This policy describes how LifeOS handles information in the LifeOS application and associated Trust Center.</p>
<h2>2. Information</h2><p>Depending on features used, LifeOS may process account identity, profile information, workspace settings, tasks, CRM records, financial/invoice records, AI conversations or memories, subscription information and technical information required to operate and secure the service.</p>
<h2>3. Google authentication</h2><p>LifeOS currently uses Google authentication. The Trust Center derives the signed-in email from the authenticated Firebase user rather than asking the user to type it.</p>
<h2>4. Purpose and minimisation</h2><p>Information should be used only for disclosed purposes and only to the extent required by the relevant feature.</p>
<h2>5. AI</h2><p>LifeOS AI may process prompts and relevant context to provide requested assistance. The final policy must match the exact provider, retention, logging and backend data flow used in production.</p>
<h2>6. Payments</h2><p>Payment handling must be described according to the provider actually used. Do not publish claims about storage of payment credentials unless verified.</p>
<h2>7. Retention and deletion</h2><p>Associated data should be deleted when an account deletion workflow is completed, except where legitimate legal, security, fraud-prevention or regulatory retention applies. Actual categories and periods must be stated in the final policy.</p>
<h2>8. Contact</h2><p>Use the verified LifeOS support/grievance contact on the Contact page.</p>`},
terms:{kicker:"Legal",title:"Terms & Conditions",summary:"Terms governing use of LifeOS. Review the final production version before publication.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Acceptance</h2><p>By using LifeOS, you agree to its applicable terms and policies.</p><h2>Account</h2><p>LifeOS currently uses Google authentication. You are responsible for access to the Google account associated with your LifeOS account.</p><h2>Acceptable use</h2><p>Do not use LifeOS for unlawful activity, abuse, fraud or unauthorized access.</p><h2>AI output</h2><p>AI output is assistance and can be wrong. Review important information before relying on it.</p><h2>Subscriptions</h2><p>Paid plans, billing, cancellation and refunds are governed by the applicable subscription policy and payment provider terms.</p>`},
ai:{kicker:"LifeOS AI",title:"AI Terms & Disclaimer",summary:"AI can accelerate planning and execution, but important decisions still require human review.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>What LifeOS AI does</h2><p>LifeOS AI can assist with planning, research, drafting, organization and analysis.</p><h2>Accuracy</h2><p>AI can produce incomplete, outdated or incorrect information. Verify important information against appropriate primary sources or qualified professionals.</p><h2>Legal and financial use</h2><p>AI responses are not a substitute for a lawyer, accountant, financial adviser or other qualified professional.</p><h2>Personal data</h2><p>Do not provide sensitive information unless necessary for the task and you understand the relevant data flow.</p>`},
subscriptions:{kicker:"Billing",title:"Subscriptions, Cancellation & Refunds",summary:"Billing information must match the real payment-provider source of truth.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Plans</h2><p>Current product tiers are Free — Essential, Starter — ₹199, Pro — ₹699 and Master — ₹1,999. Confirm billing periods and live prices before publication.</p><h2>Billing</h2><p>Subscription state shown in the Trust Center must come from the authenticated backend and payment-provider records, not a client-only flag.</p><h2>Cancellation</h2><p>Cancellation must stop future renewal according to the actual provider rules. A local downgrade alone is not a real billing cancellation.</p><h2>Refunds</h2><p>Refund eligibility and timing must match the actual payment provider and final LifeOS policy.</p>`},
permissions:{kicker:"Transparency",title:"Data & Permissions",summary:"A plain-language guide to app permissions and why a feature may need them.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Account identity</h2><p>Google authentication establishes LifeOS account identity.</p><h2>Notifications</h2><p>Notifications may be used for supported reminders, alerts or product communications. Confirm exact categories and controls in production.</p><h2>Microphone / speech</h2><p>If voice input is enabled, microphone access supports the requested voice feature. Confirm exact processing and retention before publication.</p><h2>Location</h2><p>If a LifeOS feature requests location, describe its exact purpose, foreground/background use and retention from the production implementation.</p>`},
analytics:{kicker:"Transparency",title:"Analytics Disclosure",summary:"Analytics wording must match the SDKs actually present in the production build.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Verification first</h2><p>Disclose analytics only after checking the production dependency graph, initialization and event flows.</p><h2>If Firebase Analytics is enabled</h2><p>Describe the SDK, event categories, purposes, retention and controls accurately.</p><h2>If it is not enabled</h2><p>Do not claim an external analytics service is collecting data.</p>`},
security:{kicker:"Security",title:"Security & Data Protection",summary:"Security claims must describe implemented controls, not aspirations.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Authentication</h2><p>LifeOS uses Google authentication in the current product flow.</p><h2>Account controls</h2><p>The Trust Center uses authenticated Firebase identity and server-side LifeOS account verification before exposing account controls.</p><h2>Sensitive actions</h2><p>Account deletion is treated as sensitive and recent authentication may be required.</p><h2>Client secrets</h2><p>Service-account credentials and administrative secrets must never be shipped in this static website.</p>`},
dpdp:{kicker:"India",title:"DPDP Act 2023 & DPDP Rules 2025",summary:"Privacy practices should match the Digital Personal Data Protection Act, 2023 and notified Rules, 2025, including applicable commencement dates.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Transparency</h2><p>Provide clear notice about personal-data processing, purposes and user controls.</p><h2>Purpose limitation & minimisation</h2><p>Process personal data for specified purposes and limit it to what is necessary.</p><h2>Security</h2><p>Maintain appropriate technical and organisational safeguards.</p><h2>Deletion and retention</h2><p>Delete personal data when the purpose is fulfilled, subject to lawful retention requirements.</p><h2>Applicability</h2><p>The DPDP Rules 2025 were notified with phased commencement. Final documentation should reflect provisions applicable to LifeOS at the relevant time.</p><p>This page is informational, not a legal opinion.</p>`},
contact:{kicker:"Support",title:"Contact & Grievance",summary:"Use the verified public support contact for LifeOS.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Support</h2><p>Replace this section with the real LifeOS support email/channel before publication.</p><h2>Privacy / grievance</h2><p>Privacy, personal-data and deletion requests should be handled through the official support/grievance channel.</p>`},
licenses:{kicker:"Open source",title:"Open Source Licenses",summary:"List the third-party libraries and licenses used by the website before production publication.",updated:"REPLACE BEFORE PUBLICATION",body:`
<h2>Website dependencies</h2><p>The website imports Firebase Web SDK modules from Google's CDN. Add the applicable license/attribution text for the exact production versions used.</p>`
}};
